INSERT INTO fabricante (id, name) VALUES(1, 'Intel');
INSERT INTO fabricante (id, name) VALUES(2, 'AMD');
INSERT INTO fabricante (id, name) VALUES(3, 'NVIDIA');
INSERT INTO fabricante (id, name) VALUES(4, 'Samsung');
INSERT INTO fabricante (id, name) VALUES(5, 'Western Digital');
INSERT INTO fabricante (id, name) VALUES(6, 'Seagate');
INSERT INTO fabricante (id, name) VALUES(7, 'ASUS');
INSERT INTO fabricante (id, name) VALUES(8, 'MSI');
INSERT INTO fabricante (id, name) VALUES(9, 'Corsair');
INSERT INTO fabricante (id, name) VALUES(10, 'Kingston');

INSERT INTO producto (id, name, price, id_fabricante) VALUES(1, 'Intel Core i9-11900K', 499.99, 1);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(2, 'Intel Core i7-10700K', 379.99, 1);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(3, 'AMD Ryzen 9 5950X', 799.99, 2);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(4, 'AMD Ryzen 7 5800X', 449.99, 2);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(5, 'NVIDIA GeForce RTX 3080', 699.99, 3);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(6, 'NVIDIA GeForce RTX 3070', 499.99, 3);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(7, 'Samsung 970 EVO 1TB SSD', 139.99, 4);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(8, 'Samsung 870 QVO 2TB SSD', 179.99, 4);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(9, 'Western Digital Black 2TB HDD', 89.99, 5);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(10, 'Western Digital Blue 1TB SSD', 99.99, 5);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(11, 'Seagate Barracuda 2TB HDD', 59.99, 6);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(12, 'Seagate FireCuda 1TB SSHD', 109.99, 6);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(13, 'ASUS ROG Strix B550-F Motherboard', 189.99, 7);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(14, 'ASUS TUF Gaming X570-PLUS Motherboard', 209.99, 7);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(15, 'MSI MPG Z490 Gaming Edge Motherboard', 179.99, 8);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(16, 'MSI B450 Tomahawk Max Motherboard', 139.99, 8);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(17, 'Corsair Vengeance LPX 16GB DDR4', 79.99, 9);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(18, 'Corsair RM850x 850W Power Supply', 129.99, 9);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(19, 'Kingston A2000 1TB NVMe SSD', 124.99, 10);
INSERT INTO producto (id, name, price, id_fabricante) VALUES(20, 'Kingston HyperX Fury 16GB DDR4', 89.99, 10);